exp: "087"
seed: 10
task_type: "detect"

# data preprocess
remove_prefix: true
exter_dataset:
  - ["nicholas", true]
  - ["mpware", false]
  - ["pjma", false]

n_fold: 3
use_fold: 3

# dataset, dataloader
add_newline_token: true
max_length: 128
train_stride: 96
eval_stride: 64
train_batch: 16
eval_batch: 64

# model
model_path: "microsoft/deberta-v3-large"
class_num: 8 # with prefix -> 13, without prefix -> 8
lstm_type: "none"
use_hidden_states: 2
dropout: 0.10
hidden_dropout: 0.10
attention_dropout: 0.10
reinit_layer_num: 0
freeze_layer_num: 0

# loss
smooth_type: "none"
smooth_ratio: 0.05
smooth_pair: 0.05
positive_class_weight: 10

# optimizer
optimizer_type: "AdamW"
pretrained_lr: 1e-6
head_lr: 1e-4
weight_decay: 0.01
betas: [0.9, 0.999]

# scheduler
scheduler_type: "cosine_custom"
first_cycle_epochs: 1
cycle_factor: 1
num_warmup_steps: 100
min_lr: 1e-9
gamma: 1.0

# training
epochs: 4
accumulation_steps: 2
eval_steps: 1000
negative_th: 0.660
device: "cuda"
amp: true
ema: true
ema_decay: 0.999
ema_update_after_step: 8000

# additional training
add_train: true
add_epochs: 2

# full training
full_train: true
