# general
exp: "082"
run_type: "train"
task_type: "detect"
seed: 10

# data preprocess
remove_prefix: false
exter_dataset:
  - ["nicholas", false]
  - ["mpware", false]
  - ["pjma", false]

# dataset, dataloader
add_newline_token: true
max_length: 512
train_stride: 384
eval_stride: 256
train_batch: 2
eval_batch: 4

# model
model_path: "microsoft/deberta-v3-large"
class_num: 13 # with prefix -> 13, without prefix -> 8

# loss
smooth_type: "none"
smooth_ratio: 0.05
smooth_pair: 0.05
positive_class_weight: 10

# scheduler
first_cycle_epochs: 8

# training
epochs: 8
accumulation_steps: 8
eval_steps: 1000
negative_th: 0.660
negative_th_method: "overall"
amp: true
ema: true
ema_decay: 0.999
ema_update_after_step: 8000

# additional training
add_train: true
add_epochs: 8
add_first_cycle_epochs: 8

# full training
full_train: true
