exp: "118"
first_exp: "087"
run_type: "train"
task_type: "classify"
device: "cuda"
seed: 10

# data preprocess
first_negative_th: 0.350
n_fold: 3
use_fold: 3

# dataset, dataloader
add_newline_token: true
max_length: 1536
train_stride: 768
eval_stride: 768
train_batch: 1
eval_batch: 2

# model
model_path: "microsoft/deberta-v3-large"
class_num: 1

# loss
smooth_type: "none"
smooth_ratio: 0.05
smooth_pair: 0.05
positive_class_weight: 10

# scheduler
first_cycle_epochs: 4

# training
epochs: 4
accumulation_steps: 16
eval_steps: 1000
amp: true
ema: true
ema_decay: 0.999
ema_update_after_step: 8000

# full training
full_train: true
