name: Ruff

on: [push, pull_request]
  paths:
    - '**/*.py'

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: chartboost/ruff-action@v1
        with:
          args: "check --diff"
      - name: Format
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check --diff"
