name: Ruff

on: 
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: astral-sh/ruff-action@v1
        with:
          args: "check --fix"
      - name: Format
        uses: astral-sh/ruff-action@v1
        with:
          args: "format"
      - name: Commit
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "GitHub Actions: Ruff Applied"
          git push origin main
